services:
  db:
    image: mysql:8.0
    container_name: huit-db
    restart: always
    env_file: .env
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - huit-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "huit_dc", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - webnet

  huit-bot:
    container_name: huit-bot
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    env_file: .env
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - huit-bot
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email learn.program.hoku@gmail.com --agree-tos --no-eff-email
      -d api.huitgroup.net -d www.api.huitgroup.net"
    depends_on:
      - nginx
    networks:
      - webnet


networks:
  webnet:
    driver: bridge

volumes:
  huit-volume:
