services:
  db:
    image: mysql:8.0
    container_name: huit-db
    restart: always
    env_file: .env
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "huit_dc", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - webnet

  huit-bot:
    container_name: huit-bot
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    env_file: .env
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - huit-bot
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
