services:
  db:
    image: postgres:16.2
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:3306
    command: -p ${POSTGRES_PORT}

  huit-bot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
