services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "huit_dc", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      retries: 10
      start_period: 10s

  huit-bot:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
