services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  huit-bot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
