handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/discord.log
    encoding: utf-8
    mode: w

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    standard:
      format: "%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout

    huit:
      class: loggers.DiscordHandler
      level: WARNING
      formatter: standard

  loggers:
    huit_logger:
      level: DEBUG
      handlers: [console, huit]
      propagate: false

    same_hierarchy:
      level: DEBUG
      handlers: [console, huit]
      propagate: false

    lower.sub:
      level: DEBUG
      handlers: [console, huit]
      propagate: false

  root:
    level: INFO
    handlers: [console]
