version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/discord.log
    encoding: utf-8
    mode: w

loggers:
  huitLogger:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: false

  same_hierarchy:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: false

  lower.sub:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: false

root:
  level: INFO
  handlers: [consoleHandler]
