name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GCE_SSH_KEY }}

    - name: Add GCE host to known_hosts
      run: |
        ssh-keyscan -p 533 ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

    - name: Restore nginx.conf from secret
      run: |
        echo "$NGINX_CONF" > nginx/nginx.conf
      env:
        NGINX_CONF: ${{ secrets.NGINX_CONF }}

    - name: Restore .env from secret
      run: |
        echo "$ENV_FILE" > .env
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}

    - name: Deploy
      run: |
        ssh user@${{ secrets.GCE_HOST }} -p 533 << 'EOF'
          cd /huit-app/discord-bot-py

          # Pull latest code just in case
          sudo git pull origin main

          # Check if only huit-bot changed
          if git diff --name-only HEAD~1 HEAD | grep -q '^src/'; then
            sudo docker compose up -d --build huit-bot
          else
            sudo docker compose up -d --build
          fi

          # sudo docker image prune -f  # optional: clean up unused images
        EOF
      env:
        NGINX_CONF: ${{ secrets.NGINX_CONF }}
