name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GCE_SSH_KEY }}

    - name: Restore nginx.conf from secret
      run: |
        echo "$NGINX_CONF" > nginx.conf
      env:
        NGINX_CONF: ${{ secrets.NGINX_CONF }}

    - name: Deploy
      run: |
        ssh user@${{ secrets.GCE_HOST }} << 'EOF'
          cd /huit-app/

          # Pull latest code just in case
          git pull origin main

          # Check if only huit-bot changed
          if git diff --name-only HEAD~1 HEAD | grep -q '^src/'; then
            docker compose up -d --build huit-bot
          else
            docker compose up -d --build
          fi

          docker image prune -f  # optional: clean up unused images
        EOF
      env:
        NGINX_CONF: ${{ secrets.NGINX_CONF }}
